import type { ChronoScopeClassNames } from "../../types";

/**
 * Bootstrap 5 preset — dark variant.
 *
 * Uses Bootstrap 5 utility classes and component patterns.
 * Requires Bootstrap 5.3+ (supports dark mode utilities).
 *
 * @example
 * ```tsx
 * import { ChronoScope } from "chronoscope-react";
 * import { bootstrapDark } from "chronoscope-react/presets/bootstrap";
 *
 * <ChronoScope classNames={bootstrapDark} />
 * ```
 */
export const bootstrapDark: ChronoScopeClassNames = {
  root: "d-flex align-items-center gap-2 font-monospace small",
  toolbar: "d-flex align-items-center gap-2 flex-wrap",
  toolbarNavGroup: "btn-group btn-group-sm",
  navButton: "btn btn-outline-secondary btn-sm d-flex align-items-center",
  navButtonIcon: "",
  triggerWrapper: "position-relative flex-grow-1",
  trigger: "btn btn-outline-secondary w-100 d-flex align-items-center gap-2 text-start font-monospace small",
  triggerOpen: "btn-outline-info border-info",
  triggerIcon: "text-secondary flex-shrink-0",
  triggerLabel: "flex-grow-1 text-truncate",
  triggerChevron: "text-secondary flex-shrink-0",
  liveButton: "btn btn-outline-secondary btn-sm d-flex align-items-center gap-1 text-uppercase fw-bold small",
  liveButtonActive: "btn-outline-success border-success text-success",
  liveDot: "rounded-circle bg-secondary d-inline-block",
  liveDotActive: "bg-success",
  dropdown: "position-absolute z-3 mt-1 rounded-3 border border-secondary bg-dark shadow-lg overflow-hidden",
  dropdownContent: "overflow-auto",
  tabList: "nav nav-tabs border-bottom border-secondary px-1 pt-1",
  tab: "nav-link d-flex align-items-center justify-content-center gap-1 flex-fill text-secondary small fw-semibold border-0 rounded-top cursor-pointer",
  tabActive: "nav-link active text-info border-bottom border-2 border-info bg-transparent",
  tabIcon: "",
  tabLabel: "",
  quickPanel: "p-3",
  quickSearch: "form-control form-control-sm bg-dark text-light border-secondary font-monospace mb-2",
  quickList: "list-group list-group-flush",
  quickItem: "list-group-item list-group-item-action bg-transparent text-light border-0 d-flex justify-content-between align-items-center px-3 py-2 small cursor-pointer",
  quickItemActive: "list-group-item-action bg-info bg-opacity-10 text-info",
  quickItemLabel: "",
  quickItemDot: "badge rounded-pill bg-info p-1",
  quickEmpty: "text-center text-secondary py-4 small",
  absolutePanel: "p-3",
  calendarRow: "d-flex gap-2 align-items-start mb-3",
  calendarDivider: "d-flex align-items-center text-secondary",
  calendar: "flex-grow-1",
  calendarLabel: "text-uppercase text-secondary fw-bold small mb-2",
  calendarHeader: "d-flex align-items-center justify-content-between mb-2",
  calendarNavButton: "btn btn-sm btn-link text-secondary p-0",
  calendarTitle: "fw-semibold text-light small",
  calendarWeekRow: "d-grid gap-1 mb-1",
  calendarWeekDay: "text-center text-secondary fw-semibold small",
  calendarGrid: "d-grid gap-1",
  calendarDayEmpty: "",
  calendarDay: "btn btn-sm btn-link text-light text-decoration-none p-1 rounded font-monospace",
  calendarDayToday: "border border-info text-info fw-bold",
  calendarDaySelected: "btn-info text-dark fw-bold",
  calendarDayInRange: "bg-info bg-opacity-10",
  calendarDayDisabled: "text-secondary opacity-25 pe-none",
  timeRow: "d-flex gap-3 mb-3",
  timeInput: "flex-grow-1 d-flex align-items-center gap-2",
  timeInputLabel: "text-uppercase text-secondary fw-bold small",
  timeInputFields: "input-group input-group-sm",
  timeInputField: "form-control form-control-sm bg-dark text-light border-secondary text-center font-monospace",
  timeInputSeparator: "input-group-text bg-dark text-secondary border-secondary",
  timeInputPeriod: "btn btn-sm btn-outline-info",
  absoluteFooter: "d-flex align-items-center justify-content-between gap-2 flex-wrap",
  absoluteRangeDisplay: "d-flex align-items-center gap-1 text-secondary small flex-wrap",
  absoluteRangeLabel: "fw-semibold",
  absoluteRangeValue: "badge bg-secondary bg-opacity-25 text-light font-monospace",
  absoluteRangeSeparator: "text-secondary",
  applyButton: "btn btn-info btn-sm fw-bold",
  relativePanel: "p-4",
  relativeDescription: "text-secondary small mb-4",
  relativeAccent: "text-info fw-semibold",
  relativeForm: "d-flex align-items-center gap-2 mb-4",
  relativeFormLabel: "fw-semibold text-light small",
  relativeFormInput: "form-control form-control-sm bg-dark text-light border-secondary font-monospace",
  relativeFormSelect: "form-select form-select-sm bg-dark text-light border-secondary font-monospace",
  relativePreview: "d-flex align-items-center gap-2 mb-4 p-2 rounded bg-info bg-opacity-10 border border-info border-opacity-25",
  relativePreviewLabel: "text-uppercase text-secondary fw-bold small",
  relativePreviewValue: "text-info font-monospace small",
};

/**
 * Bootstrap 5 preset — light variant.
 */
export const bootstrapLight: ChronoScopeClassNames = {
  root: "d-flex align-items-center gap-2 font-monospace small",
  toolbar: "d-flex align-items-center gap-2 flex-wrap",
  toolbarNavGroup: "btn-group btn-group-sm",
  navButton: "btn btn-outline-secondary btn-sm d-flex align-items-center",
  navButtonIcon: "",
  triggerWrapper: "position-relative flex-grow-1",
  trigger: "btn btn-outline-secondary w-100 d-flex align-items-center gap-2 text-start font-monospace small",
  triggerOpen: "btn-outline-primary border-primary",
  triggerIcon: "text-muted flex-shrink-0",
  triggerLabel: "flex-grow-1 text-truncate",
  triggerChevron: "text-muted flex-shrink-0",
  liveButton: "btn btn-outline-secondary btn-sm d-flex align-items-center gap-1 text-uppercase fw-bold small",
  liveButtonActive: "btn-outline-success border-success text-success",
  liveDot: "rounded-circle bg-secondary d-inline-block",
  liveDotActive: "bg-success",
  dropdown: "position-absolute z-3 mt-1 rounded-3 border bg-white shadow-lg overflow-hidden",
  dropdownContent: "overflow-auto",
  tabList: "nav nav-tabs px-1 pt-1",
  tab: "nav-link d-flex align-items-center justify-content-center gap-1 flex-fill text-muted small fw-semibold border-0 rounded-top cursor-pointer",
  tabActive: "nav-link active text-primary border-bottom border-2 border-primary",
  tabIcon: "",
  tabLabel: "",
  quickPanel: "p-3",
  quickSearch: "form-control form-control-sm font-monospace mb-2",
  quickList: "list-group list-group-flush",
  quickItem: "list-group-item list-group-item-action d-flex justify-content-between align-items-center px-3 py-2 small cursor-pointer",
  quickItemActive: "list-group-item-action active bg-primary bg-opacity-10 text-primary border-0",
  quickItemLabel: "",
  quickItemDot: "badge rounded-pill bg-primary p-1",
  quickEmpty: "text-center text-muted py-4 small",
  absolutePanel: "p-3",
  calendarRow: "d-flex gap-2 align-items-start mb-3",
  calendarDivider: "d-flex align-items-center text-muted",
  calendar: "flex-grow-1",
  calendarLabel: "text-uppercase text-muted fw-bold small mb-2",
  calendarHeader: "d-flex align-items-center justify-content-between mb-2",
  calendarNavButton: "btn btn-sm btn-link text-muted p-0",
  calendarTitle: "fw-semibold small",
  calendarWeekRow: "d-grid gap-1 mb-1",
  calendarWeekDay: "text-center text-muted fw-semibold small",
  calendarGrid: "d-grid gap-1",
  calendarDayEmpty: "",
  calendarDay: "btn btn-sm btn-link text-dark text-decoration-none p-1 rounded font-monospace",
  calendarDayToday: "border border-primary text-primary fw-bold",
  calendarDaySelected: "btn-primary text-white fw-bold",
  calendarDayInRange: "bg-primary bg-opacity-10",
  calendarDayDisabled: "text-muted opacity-25 pe-none",
  timeRow: "d-flex gap-3 mb-3",
  timeInput: "flex-grow-1 d-flex align-items-center gap-2",
  timeInputLabel: "text-uppercase text-muted fw-bold small",
  timeInputFields: "input-group input-group-sm",
  timeInputField: "form-control form-control-sm text-center font-monospace",
  timeInputSeparator: "input-group-text",
  timeInputPeriod: "btn btn-sm btn-outline-primary",
  absoluteFooter: "d-flex align-items-center justify-content-between gap-2 flex-wrap",
  absoluteRangeDisplay: "d-flex align-items-center gap-1 text-muted small flex-wrap",
  absoluteRangeLabel: "fw-semibold",
  absoluteRangeValue: "badge bg-light text-dark font-monospace",
  absoluteRangeSeparator: "text-muted",
  applyButton: "btn btn-primary btn-sm fw-bold",
  relativePanel: "p-4",
  relativeDescription: "text-muted small mb-4",
  relativeAccent: "text-primary fw-semibold",
  relativeForm: "d-flex align-items-center gap-2 mb-4",
  relativeFormLabel: "fw-semibold small",
  relativeFormInput: "form-control form-control-sm font-monospace",
  relativeFormSelect: "form-select form-select-sm font-monospace",
  relativePreview: "d-flex align-items-center gap-2 mb-4 p-2 rounded bg-primary bg-opacity-10 border border-primary border-opacity-25",
  relativePreviewLabel: "text-uppercase text-muted fw-bold small",
  relativePreviewValue: "text-primary font-monospace small",
};
